export default {
  allmatches: [
    {
      field: "Canchas Sinteticas El Poblado",
      cta: "Ver Detalles",
      horizontal: true,
      date: "Sabado, Junio 20",
      time: "7:00 pm",
      players: "10",
      confirmedPlayers: "2",
      remainingPlayers: "8",
    },
    {
      field: "Canchas El Escorpion",
      cta: "Ver Detalles",
      horizontal: true,
      date: "Lunes, Junio 27",
      time: "4:30 pm",
      players: "11",
      confirmedPlayers: "10",
      remainingPlayers: "1",
    },
    {
      field: "Joga Bonito Synthetic Fields",
      cta: "Ver Detalles",
      horizontal: true,
      date: "Martes, Junio 28",
      time: "10:00 am",
      players: "10",
      confirmedPlayers: "5",
      remainingPlayers: "5",
    },
    
  ],

  todayMatches: [
    {
      field: "Canchas Sinteticas El Poblado",
      cta: "Ver Detalles",
      horizontal: true,
      date: "Sabado, Junio 20",
      time: "7:00 pm",
      players: "10",
      confirmedPlayers: "2",
      remainingPlayers: "8",
    },
    {
      field: "Canchas El Escorpion",
      cta: "Ver Detalles",
      horizontal: true,
      date: "Lunes, Junio 27",
      time: "4:30 pm",
      players: "11",
      confirmedPlayers: "10",
      remainingPlayers: "1",
    },
    {
      field: "Joga Bonito Synthetic Fields",
      cta: "Ver Detalles",
      horizontal: true,
      date: "Martes, Junio 28",
      time: "10:00 am",
      players: "10",
      confirmedPlayers: "5",
      remainingPlayers: "5",
    },
    {
      field: "Canchas La Bombonera",
      cta: "Ver Detalles",
      horizontal: true,
      date: "Miercoles, Julio 2",
      time: "8:00 pm",
      players: "24",
      confirmedPlayers: "14",
      remainingPlayers: "10",
    },
    {
      field: "El Golazo",
      cta: "Ver Detalles",
      horizontal: true,
      date: "Sabado, juli0 20",
      time: "7:00 pm",
      players: "10",
      confirmedPlayers: "2",
      remainingPlayers: "8",
    },
  ],

  fieldsMatches: [
    {
      field: "Canchas La Bombonera",
      address: "Calle 80 67-89 barrio el Poblado",
      numberOfFields: "3",
      description:"Canchas ubicadas en una zona central de la ciudad con lugares para pasar un buen momento",
      fullDescription:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
      image: "https://www.las2orillas.co/wp-content/uploads/2019/06/cancha.png",
      cta: "Ver descripcion del lugar",
      horizontal: true,
    },
    {
      field: "Canchas El Escorpion",
      address: "Carrera 20 12-34 barrio Laureles",
      numberOfFields: "2",
      description:"Canchas semiprofesionales con escuela y club, un lugar donde jugar un buen partido",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBlrc6wFZWVEujyio8HuxyeivfqtT0UREFG3QDsttUVinw3eIagJAcXG3ENVphoiFRaU0&usqp=CAU",
      cta: "Ver descripcion del lugar",
      horizontal: true,
    },
    {
      field: "Joga Bonito Synthetic Fields",
      address: "Transversal 12 34-56 cerca al estadio Atanasio",
      numberOfFields: "5",
      description:"Entrenamiento profesional de jugadores de futbol, tenemos canchas sinteticas y de pasto",
      image: "https://i.ytimg.com/vi/jTu5NFLQpHo/maxresdefault.jpg",
      cta: "Ver descripcion del lugar",
      horizontal: true,
    },
    {
      field: "El Golazo",
      address: "Calle 80 67-89 barrio el Poblado",
      numberOfFields: "3",
      description:"Canchas Sinteticas con restaurante de comida rapida y ambiente familiar, escuela de futbol y entrenamiento funcional",
      image: "https://www.las2orillas.co/wp-content/uploads/2019/06/cancha.png",
      cta: "Ver descripcion del lugar",
      horizontal: true,
    },
  ],
};
